urls/urls.py
from django.urls import path

from . import views

app_name = "urls"
urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("<str:short>/", views.redirect, name="redirect"),
    path('<str:short>/detail/', views.detail, name='detail'),
]

urlshortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urls.urls')),
]

urls/models.py
from django.db import models

# Create your models here.
class URL(models.Model):
    def __str__(self):
        return self.url_short

    url_text = models.CharField(max_length=390)
    url_short = models.CharField(max_length=10, unique=True, null=False, blank=False)
    pub_date = models.DateTimeField("date published")

urls/views.py
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from .models import URL


def url_formatter(url):
    return url if (url.startswith("https://")) else f"https://{url}"


def index(request):
    return render(request, "urls/index.html")


def redirect(request, short):
    try:
        url_long = URL.objects.get(url_short=short).url_text
    except URL.DoesNotExist:
        return render(
            request, "urls/index.html", {"error_message": "URL doesn't exist"}
        )
    return HttpResponseRedirect(url_long)


def new(request):
    short = request.POST["url_short"]
    long = url_formatter(request.POST["url_long"])
    try:
        u = URL.objects.get(url_short=short).url_text
        return render(
            request, "urls/index.html", {"error_message": "URL already exists"}
        )  # redirect a index
    except URL.DoesNotExist:
        u = URL(url_text=long, url_short=short, pub_date=timezone.now())
        u.save()
    return render(
        request, "urls/index.html", {"error_message": "URL succesfully registered"}
    )  # redirect a index


def detail(request, short):
    try:
        u = URL.objects.get(url_short=short)
    except:
        return render(
            request, "urls/index.html", {"error_message": "URL doesn't exists"}
        )
    return render(request, "urls/detail.html", {"url": u})

urls/templates/urls/detail.html
<p> URL: {{ url.url_text }}</p>
<p> Shortened URL: {{ url.url_short }}</p>
<p> UTC date: {{ url.pub_date }}</p>

urls/templates/urls/index.html
<form action="{% url 'urls:new' %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>New URL</h1>
    </legend>
    {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <label for="url_long">Long URL</label>
    <input type="text" name="url_long" id="url_long">
    <label for="url_short">Short URL</label>
    <input type="text" name="url_short" id="url_short">
  </fieldset>
  <input type="submit" value="Submit" />
</form>